name = "ECalUDE"
version = "0.1.0"
uuid = "d2061c0f-c6c6-443c-b6fc-6eb2c7b35f9f"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GNNLux = "e8545f4d-a905-48ac-a8c4-ca114b98986d"
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
